// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using varManager.Data;

#nullable disable

namespace varManager.Migrations
{
    [DbContext(typeof(VarManagerContext))]
    [Migration("20250807184700_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("varManager.Models.Dependency", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DependencyName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("dependency");

                    b.Property<string>("VarName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("varName");

                    b.HasKey("ID");

                    b.ToTable("dependencies", (string)null);
                });

            modelBuilder.Entity("varManager.Models.HideFav", b =>
                {
                    b.Property<string>("VarName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("varName");

                    b.Property<bool>("Fav")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fav");

                    b.Property<bool>("Hide")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hide");

                    b.Property<int>("ID")
                        .HasColumnType("INTEGER");

                    b.HasKey("VarName");

                    b.ToTable("HideFav", (string)null);
                });

            modelBuilder.Entity("varManager.Models.InstallStatus", b =>
                {
                    b.Property<string>("VarName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("varName");

                    b.Property<bool>("Disabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("disabled");

                    b.Property<bool>("Installed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("installed");

                    b.HasKey("VarName");

                    b.ToTable("installStatus", (string)null);
                });

            modelBuilder.Entity("varManager.Models.SavedDependency", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DependencyName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("dependency");

                    b.Property<DateTime?>("ModiDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SavePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("VarName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("varName");

                    b.HasKey("ID");

                    b.ToTable("savedepens", (string)null);
                });

            modelBuilder.Entity("varManager.Models.Scene", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AtomType")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("atomType");

                    b.Property<bool>("IsLoadable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isLoadable");

                    b.Property<bool>("IsPreset")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isPreset");

                    b.Property<string>("PreviewPic")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("previewPic");

                    b.Property<string>("ScenePath")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("scenePath");

                    b.Property<string>("VarName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("varName");

                    b.HasKey("ID");

                    b.ToTable("scenes", (string)null);
                });

            modelBuilder.Entity("varManager.Models.Var", b =>
                {
                    b.Property<string>("VarName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("varName");

                    b.Property<int?>("Appearance")
                        .HasColumnType("INTEGER")
                        .HasColumnName("appearance");

                    b.Property<int?>("Asset")
                        .HasColumnType("INTEGER")
                        .HasColumnName("asset");

                    b.Property<int?>("Cloth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cloth");

                    b.Property<string>("CreatorName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("creatorName");

                    b.Property<int?>("DependencyCnt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("dependencyCnt");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int?>("Hair")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hair");

                    b.Property<int?>("Look")
                        .HasColumnType("INTEGER")
                        .HasColumnName("look");

                    b.Property<DateTime?>("MetaDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("metaDate");

                    b.Property<int?>("Morph")
                        .HasColumnType("INTEGER")
                        .HasColumnName("morph");

                    b.Property<string>("PackageName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("packageName");

                    b.Property<int?>("Plugin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("plugin");

                    b.Property<int?>("Pose")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pose");

                    b.Property<int?>("Scene")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scene");

                    b.Property<int?>("Script")
                        .HasColumnType("INTEGER")
                        .HasColumnName("script");

                    b.Property<int?>("Skin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("skin");

                    b.Property<int?>("SubScene")
                        .HasColumnType("INTEGER")
                        .HasColumnName("subScene");

                    b.Property<int?>("Texture")
                        .HasColumnType("INTEGER")
                        .HasColumnName("texture");

                    b.Property<DateTime?>("VarDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("varDate");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("version");

                    b.HasKey("VarName");

                    b.ToTable("vars", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
